{
  config,
  lib,
  pkgs,
  ...
}:
let
  throneSystemTheme = pkgs.writeShellScript "start-throne-with-system-theme" ''
    set -eu

    # Throne stores settings as key/value rows in SQLite. Its built-in themes
    # replace Qt's palette, so keep it on System and let qt6ct/Darkly provide the
    # palette generated by iNiR.
    for db in \
      "''${XDG_CONFIG_HOME:-$HOME/.config}/Throne/config/throne.db" \
      "''${XDG_CONFIG_HOME:-$HOME/.config}/throne/config/throne.db"
    do
      if [ -f "$db" ]; then
        ${pkgs.sqlite}/bin/sqlite3 "$db" \
          "INSERT INTO settings(key, value) VALUES('theme', 'System') ON CONFLICT(key) DO UPDATE SET value='System';" \
          >/dev/null 2>&1 || true
      fi
    done

    exec ${pkgs.coreutils}/bin/env \
      QT_QPA_PLATFORMTHEME=qt6ct \
      QT_STYLE_OVERRIDE=Darkly \
      /run/current-system/sw/bin/Throne
  '';
in
{
  # PrismLauncher has its own application-theme selector. "system" preserves
  # its data and accounts while making it use the Qt palette captured at start.
  home.activation.configurePrismLauncherSystemTheme =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      cfg="${config.home.homeDirectory}/.local/share/PrismLauncher/prismlauncher.cfg"
      ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$cfg")"
      ${pkgs.kdePackages.kconfig}/bin/kwriteconfig6 \
        --file "$cfg" \
        --group General \
        --key ApplicationTheme \
        system
    '';

  # Override the existing autostart command so the database theme is corrected
  # before every Throne launch, including after Throne rewrites its settings.
  systemd.user.services.throne-autostart.Service = {
    ExecStart = lib.mkForce throneSystemTheme;
    Environment = [
      "QT_QPA_PLATFORMTHEME=qt6ct"
      "QT_STYLE_OVERRIDE=Darkly"
    ];
  };
}
