{
  config,
  lib,
  pkgs,
  ...
}:
let
  throneSystemTheme = pkgs.writeShellScript "start-throne-with-system-theme" ''
    set -eu

    # Throne stores settings as key/value rows in SQLite. Its built-in themes
    # replace Qt's palette, so keep it on System and let KDE/Darkly provide the
    # palette generated by iNiR.
    for db in \
      "''${XDG_CONFIG_HOME:-$HOME/.config}/Throne/config/throne.db" \
      "''${XDG_CONFIG_HOME:-$HOME/.config}/throne/config/throne.db"
    do
      if [ -f "$db" ]; then
        ${pkgs.sqlite}/bin/sqlite3 "$db" \
          "INSERT INTO settings(key, value) VALUES('theme', 'System') ON CONFLICT(key) DO UPDATE SET value='System';" \
          >/dev/null 2>&1 || true
      fi
    done

    exec ${pkgs.coreutils}/bin/env \
      QT_QPA_PLATFORMTHEME=kde \
      QT_STYLE_OVERRIDE=Darkly \
      /run/current-system/sw/bin/Throne
  '';
in
{
  home.activation.configureSharedQtApplicationThemes =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      prism_cfg="${config.home.homeDirectory}/.local/share/PrismLauncher/prismlauncher.cfg"
      if [ -f "$prism_cfg" ]; then
        ${pkgs.gnused}/bin/sed -i \
          's/^ApplicationTheme=.*/ApplicationTheme=system/' \
          "$prism_cfg"
      fi

      dolphin_cfg="${config.xdg.configHome}/dolphinrc"
      if [ -f "$dolphin_cfg" ]; then
        ${pkgs.gnused}/bin/sed -i '/^ColorScheme=/d' "$dolphin_cfg"
      fi
    '';

  systemd.user.services.throne-autostart.Service = {
    ExecStart = lib.mkForce throneSystemTheme;
    Environment = [
      "QT_QPA_PLATFORMTHEME=kde"
      "QT_STYLE_OVERRIDE=Darkly"
    ];
  };
}
