{
  config,
  inputs,
  lib,
  osConfig,
  pkgs,
  ...
}:
{
  imports = [ inputs.inir.homeModules.inir ];

  # Use exactly the package configured by the NixOS iNiR module. Home Manager
  # only exposes it in the user profile and creates the traditional Quickshell
  # config symlink; the NixOS module remains the sole owner of inir.service.
  programs.inir = {
    enable = true;
    package = osConfig.programs.inir.package;
    service.enable = false;
    configSymlink.enable = true;
  };

  # `inir doctor` targets the mutable repo installer. On NixOS its auto-fixes
  # can shadow the wrapped launcher and point shells at a nonexistent mutable
  # venv. Remove only files/blocks carrying doctor's own identifying markers.
  home.activation.removeDoctorInirFiles = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    launcher="${config.home.homeDirectory}/.local/bin/inir"
    if [ -f "$launcher" ] && [ ! -L "$launcher" ] \
      && ${pkgs.gnugrep}/bin/grep -q 'Usage: inir' "$launcher" \
      && ${pkgs.gnugrep}/bin/grep -q 'cleanup-orphans' "$launcher"
    then
      ${pkgs.coreutils}/bin/rm -f "$launcher"
    fi

    fish_env="${config.xdg.configHome}/fish/conf.d/inir-env.fish"
    if [ -f "$fish_env" ] \
      && ${pkgs.gnugrep}/bin/grep -q 'auto-generated by doctor' "$fish_env"
    then
      ${pkgs.coreutils}/bin/rm -f "$fish_env"
    fi

    for profile in \
      "${config.home.homeDirectory}/.bashrc" \
      "${config.home.homeDirectory}/.zshrc"
    do
      if [ -f "$profile" ] && [ -w "$profile" ] \
        && ${pkgs.gnugrep}/bin/grep -q '^# iNiR environment$' "$profile" \
        && ${pkgs.gnugrep}/bin/grep -q '^# end iNiR$' "$profile"
      then
        ${pkgs.gnused}/bin/sed -i \
          '/^# iNiR environment$/,/^# end iNiR$/d' "$profile"
      fi
    done
  '';
}
